server:
port: 8080
spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  # Секреты не должны храниться в открытом виде
  secret: zavyalovegorsergeevich1BIB220660
  expiration: 36000000